# -*- coding: utf-8 -*-
"""LVDSUSR172_Niveditha_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYR0j7m1q6OvJNvIBRCV5qECRgm6wGmh
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler, LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

df = pd.read_csv("/content/penguins_classification.csv")

df.info()

plt.figure(figsize = (20,10))
sns.boxplot(df)

numerical_columns = df.columns

# Create a box plot for each numerical column
for column in numerical_columns:
    plt.figure(figsize=(20, 6))
    sns.histplot(df[column])
    plt.title(f'Bar Plot of {column}')
    plt.xlabel(column)
    plt.ylabel('Frequency')
    plt.show()

df.isnull().sum()

df['bill_depth_mm'] = df['bill_depth_mm'].fillna(df['bill_depth_mm'].mean())

df['island'].value_counts()

le = LabelEncoder()
df['island'] = le.fit_transform(df['island'])
df['species'] = le.fit_transform(df['species'])

from sklearn.ensemble import RandomForestClassifier

x = df.drop(columns = ['species'])
y = df['species']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

model = RandomForestClassifier(n_estimators=100,random_state=42)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print("Precision: ", precision_score(y_test,y_pred))
print("Recall: ", recall_score(y_test,y_pred))
print("F1 Score: ", f1_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

