# -*- coding: utf-8 -*-
"""LVADSUSR_172.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fFiGAeWUnfEWd7mtJJug9TvXxzRIxba
"""

#1
length = float(input("Enter the length of the property (in m):"))
breadth = float(input("Enter the breadth of the property (in m):"))
area = length*breadth
if area < 20.00:
  print("Small Scale area:", area, "m2")
elif area > 20.00 and area < 50.00:
  print("Medium Scale area:", area, "m2")
else:
  print("Large Scale area:", area, "m2")

#2
height = float(input("Enter your height (in m):"))
weight = float(input("Enter your weight (in kg):"))
bmi = (weight)/(height/100)**2
if bmi < 20.00:
  print("Your BMI is less than 20. You are underweight.", "\ncurrent BMI:" ,bmi)
elif bmi > 20.00 and bmi < 25.00:
  print("Your BMI is between 20 and 25. You are normal.", "\ncurrent BMI:" ,bmi)
else:
  print("Your BMI is more than 25. You are overweight.", "\ncurrent BMI:" ,bmi)
  print("Pay attention to your health")

#3
student = {}
name = input("Name:")
grades = input("Enter Grades:")
subs = input("Enter Subjects:")
student["name"] = name
student["grades"] = grades
student["Subjects"] = subs
print(student)

#4
age = int(input("Please Enter your Age: "))
if age <= 12 :
  print("Child. Redirecting...")
if age >=13 and age <= 18:
  print("Teenager. Redirecting...")
if age >= 19 and age <= 50:
  print("Adult. Redirecting...")
else:
  print("Senior Citizen. Redirecting...")

#5
subscriber_id = [123,234,345,456,567,678,789,890,124,246,357,468,579,680]
print("Targeted Subscribers:")
for x in subscriber_id:
  if (x % 2) == 0:
    print("ID:",x)

#6
password = "Nive1912001!"
user_id = input("Enter User ID:")
pwd = input("Enter Password:")
#while password == pwd:
if password == pwd:
    print("Welcome", user_id)
else:
    print("Incorrect Password")

#7
'''
feedback_scores = []
no_of_customers = int(input("Number of participating customers: "))
for x in (0,no_of_customers):
  feed_back = int(input("Enter scores out of 10: "))
  feedback_scores.append(feed_back)
print(feed_back)
'''
feedback_scores = [1,2,4,5,5,2,7,9,0,8,2,4,1,8]
length_f = len(feedback_scores)
sum_f = sum(feedback_scores)
avg_f = sum_f/length_f
print("Average score:", avg_f)

#8
string = input("Enter your content:").split()
vowel_array = []
while x in string:
  if x in ('a','e','i','o','u'):
    x += 1
  #print(string)
  print(x)

#9
import datetime

dte = datetime.datetime.now()
date = input('enter your reminding date:')
if (date == dte):
  print("Reminder")

#10
p = float(input("Enter the principal amount: "))
noy = int(input("Enter the number of years: "))
r = float(input("Enter the rate of interest: "))
r = r/100
try:
  c = p * ((1 + r)**noy)
  a = c + p
  print("Final amount:",a)
except SystemError:
  print("Problem from the System.")
except RuntimeError:
  print("The error is from our end :(")

#11
import datetime
name = input("Your Name:")
choice = int(input("Your choice(1/2/3/4): "))
dob = input("Your Date of birth:")
dt = datetime.datetime.now()
try:
  if (choice == 1) or (choice == 2) or (choice == 3) or (choice == 4):
    print("Hello", name,"\n you have polled at", dt)
  else:
    print(TypeError)
except NameError:
  print("Invalid Name Error at",dt)
except TypeError:
  print("Invalid Datatype")

#12
num1 = float(input("Enter first number:"))
num2 = float(input("Enter Second number:"))
choice = input("Enter your choice number for\n1.Addition\n2.Subtraction\n3.Multiplication\n4.Division ")
if choice == '1':
  print("SUM:",num1+num2)
if choice == '2':
  print("DIFFRENCE:",num1-num2)
if choice == '3':
  print("PRODUCT:",num1*num2)
if choice == '4':
  try:
    division = num1/num2
    print("QUOTIENT:",division)
  except ZeroDivisionError:
    print("Invalid division by zero.")
else:
  print("Invalid choice")

#13
with open('filename.txt', 'w') as file:
    file.write("This is the content that will be written to the file.")

#14
corporate_compliance = open("/content/practice_file.txt")
print(corporate_compliance.read())
corporate_compliance.close()

#15