# -*- coding: utf-8 -*-
"""LVADSUSR172_NIVEDITHA_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qyHbzdP-rw_jjUBdYWCYBHzeOlD2oK1J
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

mall = pd.read_csv("/content/Mall_Customers.csv")
mall = mall.drop('CustomerID', axis = 1)

mall = mall.dropna()

# Plot histograms for numerical columns
for column in mall.select_dtypes(include=['float64', 'int64']).columns:
    plt.figure(figsize=(7, 3))
    sns.histplot(mall[column])
    plt.title(f'Histogram of {column}')
    plt.xlabel(column)
    plt.ylabel('Frequency')
    plt.show()

len = LabelEncoder()
mall['Gender'] = len.fit_transform(mall['Gender'])

mall.isnull().sum()

for num in range(1, 6):
  kmeans = KMeans(n_clusters=num, random_state=0)
  kmeans.fit(mall)
  labels = kmeans.labels_
  centers = kmeans.cluster_centers_
  print("Iteration:",num)
  print("labels:\n",labels)
  print("clusters:\n", centers)