# -*- coding: utf-8 -*-
"""LVADSUSR172_Niveditha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUHe0brgUG3uVVXJuXHVGkqMMAkYSoG4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns

#1
ipl_ds = pd.read_csv("/content/Final Dataset - IPL.csv")
print(ipl_ds.dtypes)

ipl_ds

#2
print("To check null values\n",ipl_ds.isnull().sum())
#a)It can be inferred that there are no null values present here
print("\n\nTo check duplicates\n", ipl_ds.duplicated().value_counts())
#b) It can be inferred that there are also no duplicates present here

#3
ipl_ds.describe()

#variance
ipl_ds.describe().var()

#4
toss_df = ipl_ds[ipl_ds['match_winner'] == ipl_ds['toss_winner']]
toss_decision = toss_df['toss_decision'].value_counts()
bof = toss_decision.keys()
plt.bar(bof,toss_decision)
plt.xlabel("Toss Decision")
plt.ylabel("Count")
plt.title("Teams that won the toss and the match")

won_by = toss_df['won_by'].value_counts()
wb = won_by.keys()
plt.figure(figsize = (6,4))
plt.pie(won_by, labels = wb, data = won_by ,hatch = ['**','//'])
plt.title("Win type")
#It is evident that there are more wins while chasing

labels = ipl_ds['venue'].value_counts().keys()
plt.figure(figsize = (6,4))
plt.pie(ipl_ds['venue'].value_counts(), labels = labels)
plt.title("Venues for IPL 2022")
#mumbai has hosted the maximum of matches

first_innings = ipl_ds['first_ings_score'][(ipl_ds['stage'] == 'Group')]
second_innings = ipl_ds['second_ings_score'][(ipl_ds['stage'] == 'Group')]
plt.figure(figsize = (25,10))
plt.plot(first_innings, marker = 'o')
plt.plot(second_innings, marker = 'x')
plt.title("First Batting versus Second batting - Group Stages")
plt.xlabel("Match Number")
plt.ylabel("Runs Scored")
plt.legend(['first innings','second innings'])

first_innings = ipl_ds['first_ings_score'][(ipl_ds['stage'] != 'Group')]
second_innings = ipl_ds['second_ings_score'][(ipl_ds['stage'] != 'Group')]
plt.figure(figsize = (5,4))
plt.plot(first_innings, marker = 'o')
plt.plot(second_innings, marker = 'x')
plt.title("First Batting versus Second batting - Playoffs and Final")
plt.xlabel("Match Number")
plt.ylabel("Runs Scored")
plt.legend(['first innings','second innings'])

#5
ipl_ds.columns
colls = ipl_ds[['first_ings_score', 'first_ings_wkts','second_ings_score', 'second_ings_wkts',
       'margin', 'highscore']]
match_correlation = colls.corr()
sns.heatmap(match_correlation, annot = True)
plt.title("Correlation between innings")

#6 Outlier Detection
plt.figure(figsize = (20,10))
labels = ['first_ings_score', 'first_ings_wkts','second_ings_score', 'second_ings_wkts','margin', 'highscore']
plt.boxplot(colls, labels = labels)
plt.title("Outlier Detection")

#6 Outlier Removal
q1 = ipl_ds['margin'].quantile(0.25)
q3 = ipl_ds['margin'].quantile(0.75)

iqr = q3-q1

upper_bound = iqr + 1.5 * q3
lower_bound = iqr - 1.5 * q3
eliminated_df = [ipl_ds[(ipl_ds['margin'] > upper_bound) | (ipl_ds['margin'] < lower_bound)]]

print("Upper Bound: ", upper_bound)
print("Lower Bound: ", lower_bound)

#7
team_ven = ipl_ds[['venue','team1','team2','match_winner']]
matches_won = team_ven['match_winner'].value_counts()
teams = matches_won.keys()
cols = ['navy','pink','black','blue','red','maroon','purple', 'orange' ,'yellow','blue']
plt.figure(figsize = (15,10))
plt.bar(teams, matches_won, color = cols)
plt.title("Matches won by teams")
plt.ylabel("Matches won")
plt.xlabel("Teams")

wons = team_ven.groupby(['venue','match_winner'])['match_winner'].count().sort_values()

wons

#8
mom_counts = ipl_ds['player_of_the_match'].value_counts().head(15)
mom_player = mom_counts.keys()
plt.figure(figsize=(30,10))
plt.bar(mom_player,mom_counts)
plt.xlabel("Player")
plt.ylabel("Man Of the Match awards won")
plt.title("Who was the hottest player?")

#9
'''
1. A total of 72 matches were played
2. The maximum and minimum scores of that season were 222 and 68 respectively.
3. Kuldeep Yadav has bagged the most man of the match awards, and his performance ultimately secured
a place for him in the national team that year.
4.All the playoff matches excluding the match 2 [eliminator] were close matches.
The eliminator was won by a team batting first
5.Most of the teams won by second batting.
6. The maximum secured wins
    Wankhede Stadium, Mumbai                      Banglore        4 times
    Brabourne Stadium, Mumbai                     Delhi           4 times
'''


